; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:poesp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
        ArduinoOTA
        khoih-prog/AsyncMQTT_ESP32@^1.10.0

lib_ignore =
        WebServer_ESP32_SC_ENC
        WebServer_ESP32_SC_W5500
        WebServer_ESP32_SC_W6100
        WebServer_WT32_ETH01
        WebServer_ESP32_ENC
        WebServer_ESP32_W5500
        WebServer_ESP32_W6100

build_flags = 
	-DCORE_DEBUG_LEVEL=3
	-Wl,-Map=$BUILD_DIR/firmware.map
build_src_filter = 
	+<*>
