#include "P1P2Parser.h"

namespace
{

constexpr uint8_t CRC_GEN  = 0xD9;
constexpr uint8_t CRC_FEED = 0x00;

/*
 * Arnold P1P2MQTT bridge:
 *
 * RB = 1000
 * HB = 24 for E/F/W series
 *
 * The ATmega sends:
 *
 * R T xxx.xxx: <ASCII HEX bytes>
 *
 * Example:
 *
 * R T 123.456: 000010....
 *
 * The bridge converts the ASCII hex part to binary bytes
 * and validates the last byte as CRC.
 */

}

namespace P1P2Parser
{

uint8_t crcEseries(const uint8_t *data, uint8_t length)
{
    uint8_t crc = CRC_FEED;

    for (uint8_t i = 0; i < length; i++)
    {
        uint8_t c = data[i];

        if (CRC_GEN != 0)
        {
            for (uint8_t bit = 0; bit < 8; bit++)
            {
                crc =
                    ((crc ^ c) & 0x01)
                        ? ((crc >> 1) ^ CRC_GEN)
                        : (crc >> 1);

                c >>= 1;
            }
        }
    }

    return crc;
}

bool parseRLine(const char *line, Packet &packet)
{
    packet.length = 0;
    packet.crc = 0;
    packet.crcExpected = 0;
    packet.crcValid = false;
    packet.rawLine[0] = '\0';

    if (!line)
        return false;

    strlcpy(
        packet.rawLine,
        line,
        sizeof(packet.rawLine)
    );

    if (line[0] != 'R')
        return false;

    /*
     * Two formats generated by P1P2Monitor:
     *
     * "R T xxx.xxx: <hex...>"   -- real bus traffic, has a timestamp + colon
     * "R P         <hex...>"    -- pseudo-packet (internal state), no
     *                              timestamp/colon, just padding so the
     *                              hex payload lines up at the same column
     *
     * Previously only the colon-delimited "R T" form was handled here;
     * every "R P" line (including ATmega's own periodic 0x0E/0x0F status
     * pseudo-packets -- Control_Function, Counter_Request_Function, ATmega
     * version info, ...) was silently rejected as unparseable, since
     * strchr(line, ':') returns NULL for it.
     */

    const char *p = strchr(line, ':');

    if (p)
    {
        // "R T x.xxx: <hex>"
        p++;
    }
    else
    {
        // "R P         <hex>" -- skip 'R', whitespace, the type letter,
        // then whitespace again, to reach the start of the hex payload.
        p = line + 1;

        while (*p == ' ')
            p++;

        if (*p == '\0')
            return false;

        p++; // skip the type letter (e.g. 'P')
    }

    while (*p == ' ')
        p++;

    if (*p == '\0')
        return false;


    uint8_t count = 0;

    while (*p)
    {
        if (count >= MAX_PACKET_SIZE)
            return false;

        if (!p[0] || !p[1])
            return false;

        if (!isxdigit((unsigned char)p[0]) ||
            !isxdigit((unsigned char)p[1]))
        {
            return false;
    }


        char hex[3];

        hex[0] = p[0];
        hex[1] = p[1];
        hex[2] = '\0';

        char *endptr = nullptr;

        unsigned long value = strtoul(hex, &endptr, 16);

        if (endptr != hex + 2 || value > 0xFF)
        {
            return false;
        }

        packet.data[count++] = static_cast<uint8_t>(value);

        p += 2;
    }



    /*
     * Arnold requires at least two bytes when CRC checking
     * is enabled.
     */
    if (count < 2)
    {
        packet.length = 0;
        packet.crcValid = false;
        return false;
    }

    /*
     * Last byte is CRC.
     *
     * Arnold:
     *
     * if (CRC_GEN) rh--;
     *
     * then calculate CRC over all bytes except CRC.
     */

    const uint8_t payloadLength = count - 1;

    packet.length = payloadLength;

    packet.crc = packet.data[payloadLength];

    packet.crcExpected =
        crcEseries(packet.data, payloadLength);

    packet.crcValid =
        (packet.crc == packet.crcExpected);

    return packet.crcValid;
}

LineType parseLine(const char *line, Packet &packet)
{
    packet.length = 0;
    packet.crc = 0;
    packet.crcExpected = 0;
    packet.crcValid = false;

    if (!line || line[0] == '\0')
        return LineType::EMPTY;

    switch (line[0])
    {
        case 'R':
            if (parseRLine(line, packet))
                return LineType::PACKET;

            return LineType::ERROR;

        case 'C':
        case 'c':
            return LineType::TIMING;

        case 'D':
            return LineType::DUPLICATE;

        case 'E':
            return LineType::ERROR;

        case '*':
            return LineType::INFO;

        default:
            return LineType::INVALID;
    }
}

}
